# Generated by Django 5.2.7 on 2025-11-24 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('about', 'Sobre Nosotros'), ('social', 'Sociales'), ('corporate', 'Corporativos'), ('government', 'Gubernamentales'), ('camerinos', 'Camerinos'), ('adicionales', 'Adicionales')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra_text', models.TextField(blank=True, help_text='Texto adicional, listas, etc.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.homesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
